# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IeeU6gzKKWJ2MWsgZYsCN9W3mzAWsiAX
"""

import pandas as pd
import matplotlib.pyplot as plt

data = pd.read_csv("https://raw.githubusercontent.com/wcota/covid19br/master/cases-brazil-cities.csv")

cidade_mais_casos = data.loc[data['totalCases'].idxmax(), 'city']
print("Cidade com mais casos de COVID:", cidade_mais_casos)

cidade_menos_casos = data.loc[data['totalCases'].idxmin(), 'city']
print("Cidade com menos casos de COVID:", cidade_menos_casos)

estado_mais_casos = data.groupby('state')['totalCases'].sum().idxmax()
print("Estado com mais casos de COVID:", estado_mais_casos)

estado_menos_casos = data.groupby('state')['totalCases'].sum().idxmin()
print("Estado com menos casos de COVID:", estado_menos_casos)

cidade_mais_mortes = data.loc[data['deaths'].idxmax(), 'city']
print("Cidade com mais mortes por COVID:", cidade_mais_mortes)

cidade_menos_mortes = data.loc[data['deaths'].idxmin(), 'city']
print("Cidade com menos mortes por COVID:", cidade_menos_mortes)

estado_mais_mortes = data.groupby('state')['deaths'].sum().idxmax()
print("Estado com mais mortes por COVID:", estado_mais_mortes)

estado_menos_mortes = data.groupby('state')['deaths'].sum().idxmin()
print("Estado com menos mortes por COVID:", estado_menos_mortes)

total_casos_brasil = data['totalCases'].sum()
print("Total de casos de COVID no Brasil:", total_casos_brasil)

total_mortes_brasil = data['deaths'].sum()
print("Total de mortes por COVID no Brasil:", total_mortes_brasil)

top5_estados_mortes = data.groupby('state')['deaths'].sum().nlargest(5)
top5_estados_mortes.plot(kind='bar', title="Top 5 estados com mais mortes por COVID")
plt.xlabel("Estado")
plt.ylabel("Número de mortes")
plt.show()

bottom5_estados_mortes = data.groupby('state')['deaths'].sum().nsmallest(5)
bottom5_estados_mortes.plot(kind='bar', title="Top 5 estados com menos mortes por COVID", color='orange')
plt.xlabel("Estado")
plt.ylabel("Número de mortes")
plt.show()